version: '3.9'

services:
  jenkins:
    build: .
    container_name: jenkins-test
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./project:/app

volumes:
  jenkins_home: